### ISSUE TITLE
Unable to deploy gaffer-road-traffic chart from our hosted Helm repo

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-docker#124]
```
$ helm template traffic gaffer-docker/gaffer-road-traffic
```
`
Error: template: gaffer-road-traffic/charts/gaffer/templates/accumulo/tserver/statefulset.yaml:36:28: executing "gaffer-road-traffic/charts/gaffer/templates/accumulo/tserver/statefulset.yaml" at <include (print $.Template.BasePath "/accumulo/config.yaml") .>: error calling include: template: gaffer-road-traffic/charts/gaffer/templates/accumulo/config.yaml:132:24: executing "gaffer-road-traffic/charts/gaffer/templates/accumulo/config.yaml" at <include "gaffer.accumuloSite" .>: error calling include: template: gaffer-road-traffic/charts/gaffer/templates/accumulo/config.yaml:19:34: executing "gaffer.accumuloSite" at <include "gaffer.hdfsNamenodeHostname" .>: error calling include: template: gaffer-road-traffic/charts/gaffer/templates/_helpers.tpl:81:4: executing "callSubChartTemplate" at <include $template (dict "Chart" (dict "Name" (last $subchart)) "Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "hdfs.fullname" associated with template "gotpl"
`

**Comment by ctas582** [comment]
This error is because although the hosted gaffer-road-traffic chart tarball contains the gaffer sub-chart, it does not contain the gaffer chart's dependencies (hdfs and zookeeper).

The new release process only resolves the dependencies for the chart being released, not any nested dependencies:
https://github.com/gchq/gaffer-docker/blob/2aa4049d836d07a76fea597fbdc3624bf68640aa/.github/workflows/release.yaml#L139

We fluked this with the previous release process - globbing the kubernetes directory to find the list of charts to release always resulted in the dependencies for the gaffer chart being resolved before the gaffer-road-traffic chart!

**Comment by d47853** [comment]
Good spot. I didn't notice it as I've only been deploying the Gaffer chart from the repo
