### ISSUE TITLE
What needs to be added for release 1.0?

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-docker#167]
This project continues to evolve. What things still need to be added to create a 1.0 release?

**Comment by t92549** [comment]
I am not sure on others opinions but would suggest https://github.com/gchq/gaffer-docker/issues/133 could make it a "full" 1.0 release.
Other than that perhaps we need to think about how users may want to choose between running Gaffer 1 or Gaffer 2?

**Comment by t92549** [comment]
Closed as 1.0 is released: https://github.com/gchq/gaffer-docker/releases/tag/v1.0.0
