### ISSUE TITLE
Add Accumulo 2 support for Gaffer

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-docker#238]
With Gaffer 2 alpha 3, Accumulo 2 support has been added. gaffer-docker requires updating to allow an Accumulo 2 image to be built, as well as still supporting Accumulo 1 images. The gaffer image will also need some changes to ensure that it works with Accumulo 2 and Accumulo 1.

- [x] Get accumulo 2 building with docker
- [x] Get Gaffer 2 building with accumulo 2
- [x] Add option to build accumulo 1 or 2
- [x] Add option to build gaffer 2 with accumulo 1 or 2
- [x] Ensure Gaffer 1 cannot be built with Accumulo 2
- [x] Ensure helm charts work with Accumulo 1 or 2

**Comment by t92549** [comment]
This requires investigation on how to load in Gaffer's iterator.jars, now that default dynamic classpath reloading has been [removed](https://accumulo.apache.org/release/accumulo-2.0.0/#removed-default-dynamic-reloading-classpath-directory-libext).

**Comment by lb324567** [comment]
Completed with #250
