### ISSUE TITLE
Add optional Kerberos support

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-docker#240]
Gaffer currently connects to Accumulo using username/password, [Gaffer #2614](https://github.com/gchq/Gaffer/issues/2614) requires Kerberos authentication support to be added as well.
To effectively test this change, a new docker image for a Kerberos KDC should be added along with additional images for Accumulo, Hadoop, etc. These image changes should be optional and not the default. This will require them to be built separately, based on the existing images, not as an addition to them.

**Comment by GCHQDeveloper314** [comment]
This was originally worked on prior to the change to add support for Accumulo 2.0.1 to Gaffer Docker. A new PR now supports both versions of Accumulo. Adding support to run ITs against Accumulo will be added separately.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/gaffer-docker/pull/273
