### ISSUE TITLE
Add note to main README to indicate Docker building issues on Windows

### ISSUE THREAD

**Issue by i471828** [gchq/gaffer-docker#241]
See https://github.com/gchq/gaffer-docker/issues/98#issuecomment-1203775092

For as yet unknown reasons, building on Windows can sometimes fail.

We should add this to the main README for gaffer-docker

```
## Known issues

Some images may fail to build on Windows. We recommend either building in a Linux / Mac operating system, or if you do use Windows, build the images in a Linux virtual machine, e.g. through using VirtualBox.
```

**Comment by ctas582** [comment]
Windows building is fixed by #242
