### ISSUE TITLE
Add healthchecks to compose files

### ISSUE THREAD

**Issue by lb324567** [gchq/gaffer-docker#243]
Healthchecks make it easier to diagnose a issues with containers and also help track how ready a service is. It means that we can bring containers up in a certain order, and only if the containers they rely on are 'healthy'.
These can be defined within the Dockerfiles, but as we are using compose we can just add them there. 

The Kerberos docker-compose file has healthchecks implemented so examples of how to do this can be found there. Docker docs for healthcheck are [here](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck)

**Comment by lb324567** [comment]
Paused work on this while other work is completed

**Comment by GCHQDeveloper314** [comment]
This was mostly duplicated by #258, as healthchecks and startup ordering go hand in hand. A branch for #258 was already created, so this issue has been merged into it and is no longer required.
