### ISSUE TITLE
Update zookeeper helm dependency

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-docker#255]
As a more long term solution to https://github.com/gchq/gaffer-docker/issues/253, the helm chart for zookeeper should be updated to a more up to date one, as described in the [comment](https://github.com/gchq/gaffer-docker/issues/253#issuecomment-1240976660)

**Comment by t92549** [comment]
Perhaps use https://artifacthub.io/packages/helm/bitnami/zookeeper

**Comment by sb89594** [comment]
Can close this issue based on the above PR being merged: https://github.com/gchq/gaffer-docker/pull/374

**Comment by GCHQDeveloper314** [comment]
Closed by #374
