### ISSUE TITLE
Improve container release scripts to include legacy Accumulo version

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-docker#298]
With the Accumulo version upgraded to 2.0.1 (from 1.9.3), we are no longer pushing further updates to the existing Accumulo 1.9.3 container image.

This is a problem if we want to make changes which affect how the image is used in Docker compose or Kubernetes. For #258 there's a need to improve the Accumulo container to allow for healthchecks to be added. If the modified compose file is used with the existing Accumulo 1.9.3 container, it will fail as the last published container with Accumulo 1.9.3 doesn't contain the necessary changes. Currently, no new versions of this container are being published.

The above problem can be fixed by changing the container release scripts such that they publish updates for Accumulo 1.9.3 again.

**Comment by t92549** [comment]
Worth noting that #258 was solved in a backwards compatible way so a new container doesn't need to be pushed for that.
However, it would still be useful to push the Accumulo 1.9.3 images, as well as Gaffer2-Accumulo1 images

**Comment by t92549** [comment]
Closed by https://github.com/gchq/gaffer-docker/pull/299
