### ISSUE TITLE
Bug: Cannot install Gaffer Helm charts on Kubernetes 1.25+

### ISSUE THREAD

**Issue by sb89594** [gchq/gaffer-docker#363]
Following the instructions [here](https://gchq.github.io/gaffer-doc/latest/administration-guide/gaffer-deployment/kubernetes-guide/simple-deployment/) does not currently work and fails with:

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "my-graph-zookeeper" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first`

I believe it is because the beta version of this API was deprecated as part of Kubernetes version 1.25 ([docs here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125)).

As such, I think the Zookeeper dependency [here](https://github.com/gchq/gaffer-docker/blob/c3b06f27171b57cf22c31567bc6e93dbfc8f93cf/kubernetes/accumulo/Chart.yaml#L26) needs to be updated to use a more upto date version which does not use the beta API.

**Comment by GCHQDeveloper314** [comment]
Duplicates #255 which has some more details on this.

There are some other Helm problems currently and as Helm isn't a priority for us, we recommend using docker compose to try out Gaffer.

**Comment by sb89594** [comment]
Thank you for the response, might I suggest if Helm is no longer supported that the documentation be changed to reflect this? Or at least a warning is put on that it won't work on K8s 1.26+ and to use Docker compose instead?

**Comment by GCHQDeveloper314** [comment]
Good point, I've raised [docs #489](https://github.com/gchq/gaffer-doc/issues/489) for this.
