### ISSUE TITLE
Containerise the Federated Store

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-docker#54]
Project: https://github.com/gchq/Gaffer/tree/master/store-implementation/federated-store

Info: https://gchq.github.io/gaffer-doc/getting-started/developer-guide/federatedstore.html

**Comment by t11947** [comment]
Acceptance criteria for this ticket:

A developer can use docker-compose to start a federated REST service which can add remote accumulo graphs and federate them.

A user can use an included federated UI to query the included REST API.

A developer can provide the UI a configuration file to allow specification of non-default options such as edge/entity colours and operation options.

**Comment by d47853** [comment]
Merged into develop
