### ISSUE TITLE
Integrate gaffer-docker into Gaffer release process

### ISSUE THREAD

**Issue by t616178** [gchq/gaffer-docker#6]
When a Gaffer release is published, the gaffer-docker image should also be updated to match the new Gaffer version. The updated image should also be pushed up to Docker Hub and tagged with the 'latest' tag.

**Comment by csmallon** [comment]
Not sure if this is still being looked at, but I'd +1 this... with the exception that it gets a proper version tag as opposed to 'latest' - IIRC that isn't the intention behind the 'latest' tag.

**Comment by t616178** [comment]
Hi Chris,

At present, we've stopped supporting Docker in favour of:

* a standalone profile for small prototypes (where the graph contents can fit in memory and do not need to be persisted)
* scripts which enable Accumulo to be deployed onto a YARN cluster (via Apache Slider)

We are also looking into deployment options for creating Gaffer instances in AWS using scalable EMR clusters.

If there's further interest for the Docker solution (especially we become aware of any use cases which cannot be met by our current deployment options) we may look to support it again.

**Comment by csmallon** [comment]
I'm currently looking at modding cybermaggedon's images to allow updateability (https://hub.docker.com/r/cybermaggedon/accumulo-gaffer/).

While those sounds interesting, none of the three use cases mentioned help with any kind of stress-testing research on a closed network - the standalone profile isn't big enough to handle any use in anger and the two others require commitment to maintaining a given setup (a YARN cluster and what sounds like a traditional EC2 layout), which was why I was looking into docker containers in the first place. 

It surprising that there's no desire to support this kind of thing in Kubernetes as it seems it would work great in this scenario.

**Comment by gaffer01** [comment]
@csmallon There is a desire to support deploying Gaffer via Docker or Kubernetes, but unfortunately it's not high enough on our priority list for us to actively work on it now. We would be very happy for others to demonstrate how this can be done, provide PRs, etc.

**Comment by d47853** [comment]
Gaffer Docker is now being managed and regularly updated
