### ISSUE TITLE
REST API can't run custom Operations and Functions

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-docker#68]
Sometimes Graph owners have custom operations or operations from different libraries that they want to run through their REST API. In order to add these operations / functions, the jar files will need to be added to the classpath of the REST service, as well as the Accumulo lib/ext directory. 

Operations have a further complication in that they need to be added to the REST api using an operation declarations file. See the bottom of [this page](https://gchq.github.io/gaffer-doc/components/core/store.html) for an example

**Comment by ctas582** [comment]
This duplicates #33 and #34.

The way this is supported is for users to build their own container images, containing their custom JARs, using our containers as the base e.g.

```
FROM gchq/gaffer:1.11.0
COPY <jar> /opt/accumulo/lib/ext
```

This probably just needs documenting.

**Comment by d47853** [comment]
Oh yeah of course it does. i'll close this as a duplicate
