### ISSUE TITLE
Docker run commands

### ISSUE THREAD

**Issue by re2023** [gchq/gaffer-docker#89]
Please can I ask that you update the Gaffer document to provide basic instructions for how a new user can launch gaffer in a docker environment. 

When I run Gaffer using:

docker run -d -it -p 8080:8080 --name gaffer gchq/gaffer

The container auto stops. I assume there are some dependent packages or containers I need to run and link in first. However, I do not know what these are.

**Comment by d47853** [comment]
Hi @re2023,

Thanks for raising your issue. We tend to advise using Docker compose as Gaffer is comprised of a number of containers so using `docker run ...` can get a bit messy. We have provided some docker-compose files in the codebase. For example, if you run `docker-compose up` from the docker/gaffer folder, you'll be given a Gaffer instance with HDFS, Accumulo and Zookeeper. This is highlighted in the README.md files but it could be improved (issue #47).

Is there a reason you specifically wanted to use docker run as opposed to docker-compose?

**Comment by re2023** [comment]
No reason. I guess this was due to my ignorance using docker. I did not understand what the `docker-compose up` meant. 

Thanks for your assistance
