### ISSUE TITLE
Add Hook Delete Policy to clean up Pods created by Hooks

### ISSUE THREAD

**Issue by m29827** [gchq/gaffer-docker#94]
Pods created by hooks are not managed by Helm and as a result do not get removed when an uninstall of the chart is performed. For example Accumulo credentials for a Graph are set by the accumulo-post-install-cmds hook triggered pod, as a result it is not possible to uninstall and re-install a graph with the same name using different credentials to those used in the original install.
It's possible to get hook triggered pods to cleanup automatically on success and/or failure: https://github.com/helm/helm/pull/2692 the only downside being the logs for that pod are no longer available. 
If the accumulo-post-install-cmds pod was automatically deleted on successful completion then it would be possible to install and uninstall a graph and then re-install with different credentials.

**Comment by d47853** [comment]
Merged into develop
