### ISSUE TITLE
docker compose error: 'hdfs-namenode' failed to build

### ISSUE THREAD

**Issue by re2023** [gchq/gaffer-docker#98]
When running:
`docker-compose up`
It fails to build on on step 11 for hadoop with the following errors:
`Building hdfs-namenode
Step 1/29 : ARG BUILDER_IMAGE_NAME=debian
Step 2/29 : ARG BUILDER_IMAGE_TAG=stretch-20200224-slim
Step 3/29 : ARG BASE_IMAGE_NAME=debian
Step 4/29 : ARG BASE_IMAGE_TAG=stretch-20200224-slim
Step 5/29 : ARG HADOOP_VERSION=3.2.1
Step 6/29 : FROM ${BUILDER_IMAGE_NAME}:${BUILDER_IMAGE_TAG} as builder
 ---> 4e6990ebcef5
Step 7/29 : ARG HADOOP_VERSION
 ---> Using cache
 ---> c3425501241c
Step 8/29 : ARG HADOOP_DOWNLOAD_URL=https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz
 ---> Using cache
 ---> 95feaf235d1d
Step 9/29 : ARG HADOOP_APPLY_PATCHES=false
 ---> Using cache
 ---> 64fb2c4206d8
Step 10/29 : COPY ./files/ /
 ---> Using cache
 ---> b5bc9b6912bd
Step 11/29 : RUN ./build-hadoop.sh
 ---> Running in 84dfe0ac80ec
: invalid option
ERROR: Service 'hdfs-namenode' failed to build : The command '/bin/sh -c ./build-hadoop.sh' returned a non-zero code: 1`

**Comment by n3101** [comment]
@re2023 Apologies for the silence. I'll get someone to look into this.

**Comment by re2023** [comment]
Is there any update on this item?

**Comment by n3101** [comment]
@t92549 told you I was not docker literate. OP apparently using Debian.

**Comment by t92549** [comment]
> @t92549 told you I was not docker literate. OP apparently using Debian.

How do you know he is using Debian?

**Comment by n3101** [comment]
from the error msg:
 ARG BUILDER_IMAGE_NAME=debian 
ARG BASE_IMAGE_NAME=debian

**Comment by n3101** [comment]
@t92549 The only other thing I'd suggest is that this might be analogous to a problem I had when I tried to run this stuff - namely that things weren't started in the right order. In that case it was possible to use the docker desktop to start the missing service. This was just long enough ago for my chat with ctas to have been deleted.

**Comment by t92549** [comment]
[debian](https://hub.docker.com/_/debian/) is the base image from which we build the hdfs image. I was wondering what platform they are running docker on. Theoretically it shouldn't matter as long as it's Linux, I just haven't tested much else other than an ubuntu VM personally.

**Comment by n3101** [comment]
oh ok. I'll shut up now!

**Comment by re2023** [comment]
@n3101 this is running on docker running on windows. Apologies I am not very experienced in this area and just took the base docker images and tried to run them. 

```
#run hdsf container
docker run -d --name hdfs -p 9870:9870 -v /data/hdfs:/data gchq/hdfs
#run accumulo container
docker run -d --name accumulo -p 9995:9995 --link hdfs:hdfs gchq/accumulo
# run gaffer-rest container
docker run -d --name gaffer-rest -p 8080:8080 gchq/gaffer-rest
# run gaffer-ui container
docker run -d --name gaffer-ui -p 5000:5000 gchq/gaffer-ui
#run gaffer container and link to resources
docker run -d --name gaffer --link hdfs:hdfs --link accumulo:accumulo --link gaffer-rest:gaffer-rest --link gaffer-ui:gaffer-ui gchq/gaffer
```

Due to my lack of experience I was hoping for more explicit guidance on how to get this running. 

I have built a web app and want to connect to gaffer via the api, but am failing to get it running at this stage and not even sure if I am approaching this in the correct manner.

**Comment by t92549** [comment]
I don't have much experience using docker for Windows but it should include a VM under the hood so it can run Linux based containers.
If you want an accumulo based Gaffer like in the example you posted, this [README](https://github.com/gchq/gaffer-docker/blob/develop/docker/gaffer/README.md) and [docker-compose](https://github.com/gchq/gaffer-docker/blob/develop/docker/gaffer/docker-compose.yaml) file should explain how to do that.
If you just want to experiment with Gaffer running an in memory store rather than Accumulo you could run the [ui](https://github.com/gchq/gaffer-docker/blob/develop/docker/gaffer-ui/README.md) instead.

Ultimately though I am not sure why you get that error message that fails to build the hdfs image, it may be a Windows thing.

**Comment by re2023** [comment]
I will try that

**Comment by re2023** [comment]
Here is the result:

![image](https://user-images.githubusercontent.com/64115725/181246237-3955b69f-026c-46c1-ba75-ec206714c8ef.png)

**Comment by t92549** [comment]
It looks like the step that installs a bunch of packages is cancelled, which is why the `build-hadoop.sh` stage fails. After some googling it would seem that this can be caused by a firewall on Windows blocking docker.

If you don't mind testing this without the hdfs/Accumulo backing store, you could try just running the [rest-api](https://github.com/gchq/gaffer-docker/tree/develop/docker/gaffer-rest). This should just spin up the rest-api using an in memory MapStore rather than building hdfs and Accumulo.

**Comment by re2023** [comment]
> It looks like the step that installs a bunch of packages is cancelled, which is why the `build-hadoop.sh` stage fails. After some googling it would seem that this can be caused by a firewall on Windows blocking docker.
> 
> If you don't mind testing this without the hdfs/Accumulo backing store, you could try just running the [rest-api](https://github.com/gchq/gaffer-docker/tree/develop/docker/gaffer-rest). This should just spin up the rest-api using an in memory MapStore rather than building hdfs and Accumulo.

I have added docker to allowed applications on local FW and it still fails. 

However, you are correct that the gaffer-rest runs without issue. 

@i471828 i will try spin up a linux vm and see if it experiences the same issue.

**Comment by re2023** [comment]
@i471828 you are correct. using a Linux VM in virtual box was able to execute the docker-compose up and once the network was bridged I could connect to the ui and rest.

I believe you are correct that this must be a windows related issue and not from your build. 

I will close this. Using a Linux VM  is a good workaround and more typical of a cloud environment where this would typically be hosted.

**Comment by t92549** [comment]
Good news you got it working! Apologies there is no documentation that states there might be issues with Windows builds

**Comment by n3101** [comment]
@t92549 @re2023 "Using a Linux VM is a good workaround and more typical of a cloud environment where this would typically be hosted."

We must document this.

**Comment by re2023** [comment]
Documenting that there is a compatibility issue with windows is good. but I do not feel you would need to spend any more effort on this.

I think it is really only applicable is someone was perhaps doing development work hosted a tried to host Gaffer locally. 

I appreciate all your help, now to try and make use of Gaffer

**Comment by n3101** [comment]
@re2023 I'm not proposing a major doc effort for this, but we are currently redesigning our doc and identifying holes in it, so now is a good time for us to capture this before the knowledge is lost again.

I hope that things will go more easily for you now, but if not please contact us and we will try to respond more promptly.
